//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisBody) DeepCopyInto(out *AnalysisBody) {
	*out = *in
	if in.Systems != nil {
		in, out := &in.Systems, &out.Systems
		*out = make([]SystemsAnalysis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisBody.
func (in *AnalysisBody) DeepCopy() *AnalysisBody {
	if in == nil {
		return nil
	}
	out := new(AnalysisBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainConnectionBody) DeepCopyInto(out *BlockchainConnectionBody) {
	*out = *in
	if in.ContainerList != nil {
		in, out := &in.ContainerList, &out.ContainerList
		*out = make([]ContainerDefinitions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sensors != nil {
		in, out := &in.Sensors, &out.Sensors
		*out = make([]SensorsBlockchainConnectionBody, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainConnectionBody.
func (in *BlockchainConnectionBody) DeepCopy() *BlockchainConnectionBody {
	if in == nil {
		return nil
	}
	out := new(BlockchainConnectionBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyProperties) DeepCopyInto(out *BodyProperties) {
	*out = *in
	if in.Sensors != nil {
		in, out := &in.Sensors, &out.Sensors
		*out = make([]SensorsBody, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Contract.DeepCopyInto(&out.Contract)
	if in.RequiredTechnicalContainers != nil {
		in, out := &in.RequiredTechnicalContainers, &out.RequiredTechnicalContainers
		*out = make([]RequiredTechnicalContainersBody, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KosmosLocalSystems != nil {
		in, out := &in.KosmosLocalSystems, &out.KosmosLocalSystems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Analysis.DeepCopyInto(&out.Analysis)
	in.BlockchainConnection.DeepCopyInto(&out.BlockchainConnection)
	if in.MachineConnection != nil {
		in, out := &in.MachineConnection, &out.MachineConnection
		*out = make([]MachineConnectionBody, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Metadata = in.Metadata
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyProperties.
func (in *BodyProperties) DeepCopy() *BodyProperties {
	if in == nil {
		return nil
	}
	out := new(BodyProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionData) DeepCopyInto(out *ConnectionData) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionData.
func (in *ConnectionData) DeepCopy() *ConnectionData {
	if in == nil {
		return nil
	}
	out := new(ConnectionData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSystems) DeepCopyInto(out *ConnectionSystems) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSystems.
func (in *ConnectionSystems) DeepCopy() *ConnectionSystems {
	if in == nil {
		return nil
	}
	out := new(ConnectionSystems)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDefinitions) DeepCopyInto(out *ContainerDefinitions) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PortsContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDefinitions.
func (in *ContainerDefinitions) DeepCopy() *ContainerDefinitions {
	if in == nil {
		return nil
	}
	out := new(ContainerDefinitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractBody) DeepCopyInto(out *ContractBody) {
	*out = *in
	out.Valid = in.Valid
	if in.Partners != nil {
		in, out := &in.Partners, &out.Partners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Permissions.DeepCopyInto(&out.Permissions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractBody.
func (in *ContractBody) DeepCopy() *ContractBody {
	if in == nil {
		return nil
	}
	out := new(ContractBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsConnectionData) DeepCopyInto(out *CredentialsConnectionData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsConnectionData.
func (in *CredentialsConnectionData) DeepCopy() *CredentialsConnectionData {
	if in == nil {
		return nil
	}
	out := new(CredentialsConnectionData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KosmosKubeEdge) DeepCopyInto(out *KosmosKubeEdge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KosmosKubeEdge.
func (in *KosmosKubeEdge) DeepCopy() *KosmosKubeEdge {
	if in == nil {
		return nil
	}
	out := new(KosmosKubeEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KosmosKubeEdge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KosmosKubeEdgeList) DeepCopyInto(out *KosmosKubeEdgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KosmosKubeEdge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KosmosKubeEdgeList.
func (in *KosmosKubeEdgeList) DeepCopy() *KosmosKubeEdgeList {
	if in == nil {
		return nil
	}
	out := new(KosmosKubeEdgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KosmosKubeEdgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KosmosKubeEdgeSpec) DeepCopyInto(out *KosmosKubeEdgeSpec) {
	*out = *in
	in.Body.DeepCopyInto(&out.Body)
	out.Signature = in.Signature
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KosmosKubeEdgeSpec.
func (in *KosmosKubeEdgeSpec) DeepCopy() *KosmosKubeEdgeSpec {
	if in == nil {
		return nil
	}
	out := new(KosmosKubeEdgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KosmosKubeEdgeStatus) DeepCopyInto(out *KosmosKubeEdgeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KosmosKubeEdgeStatus.
func (in *KosmosKubeEdgeStatus) DeepCopy() *KosmosKubeEdgeStatus {
	if in == nil {
		return nil
	}
	out := new(KosmosKubeEdgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ML_TriggerPipelines) DeepCopyInto(out *ML_TriggerPipelines) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ML_TriggerPipelines.
func (in *ML_TriggerPipelines) DeepCopy() *ML_TriggerPipelines {
	if in == nil {
		return nil
	}
	out := new(ML_TriggerPipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConnectionBody) DeepCopyInto(out *MachineConnectionBody) {
	*out = *in
	in.Connector.DeepCopyInto(&out.Connector)
	out.ConnectionData = in.ConnectionData
	out.SubscribeData = in.SubscribeData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConnectionBody.
func (in *MachineConnectionBody) DeepCopy() *MachineConnectionBody {
	if in == nil {
		return nil
	}
	out := new(MachineConnectionBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaSensors) DeepCopyInto(out *MetaSensors) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaSensors.
func (in *MetaSensors) DeepCopy() *MetaSensors {
	if in == nil {
		return nil
	}
	out := new(MetaSensors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaSignature) DeepCopyInto(out *MetaSignature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaSignature.
func (in *MetaSignature) DeepCopy() *MetaSignature {
	if in == nil {
		return nil
	}
	out := new(MetaSignature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBody) DeepCopyInto(out *MetadataBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBody.
func (in *MetadataBody) DeepCopy() *MetadataBody {
	if in == nil {
		return nil
	}
	out := new(MetadataBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDefinitions) DeepCopyInto(out *ModelDefinitions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDefinitions.
func (in *ModelDefinitions) DeepCopy() *ModelDefinitions {
	if in == nil {
		return nil
	}
	out := new(ModelDefinitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionsContract) DeepCopyInto(out *PermissionsContract) {
	*out = *in
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionsContract.
func (in *PermissionsContract) DeepCopy() *PermissionsContract {
	if in == nil {
		return nil
	}
	out := new(PermissionsContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePipelines) DeepCopyInto(out *PipelinePipelines) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(ModelDefinitions)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(ModelDefinitions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePipelines.
func (in *PipelinePipelines) DeepCopy() *PipelinePipelines {
	if in == nil {
		return nil
	}
	out := new(PipelinePipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesDefinitions) DeepCopyInto(out *PipelinesDefinitions) {
	*out = *in
	out.ML_Trigger = in.ML_Trigger
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = make([]PipelinePipelines, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sensors != nil {
		in, out := &in.Sensors, &out.Sensors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesDefinitions.
func (in *PipelinesDefinitions) DeepCopy() *PipelinesDefinitions {
	if in == nil {
		return nil
	}
	out := new(PipelinesDefinitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsContainer) DeepCopyInto(out *PortsContainer) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsContainer.
func (in *PortsContainer) DeepCopy() *PortsContainer {
	if in == nil {
		return nil
	}
	out := new(PortsContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredTechnicalContainersBody) DeepCopyInto(out *RequiredTechnicalContainersBody) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerDefinitions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredTechnicalContainersBody.
func (in *RequiredTechnicalContainersBody) DeepCopy() *RequiredTechnicalContainersBody {
	if in == nil {
		return nil
	}
	out := new(RequiredTechnicalContainersBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensorsBlockchainConnectionBody) DeepCopyInto(out *SensorsBlockchainConnectionBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensorsBlockchainConnectionBody.
func (in *SensorsBlockchainConnectionBody) DeepCopy() *SensorsBlockchainConnectionBody {
	if in == nil {
		return nil
	}
	out := new(SensorsBlockchainConnectionBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensorsBody) DeepCopyInto(out *SensorsBody) {
	*out = *in
	if in.StorageDuration != nil {
		in, out := &in.StorageDuration, &out.StorageDuration
		*out = make([]StorageDurationSensors, len(*in))
		copy(*out, *in)
	}
	out.Meta = in.Meta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensorsBody.
func (in *SensorsBody) DeepCopy() *SensorsBody {
	if in == nil {
		return nil
	}
	out := new(SensorsBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureProperties) DeepCopyInto(out *SignatureProperties) {
	*out = *in
	out.Meta = in.Meta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureProperties.
func (in *SignatureProperties) DeepCopy() *SignatureProperties {
	if in == nil {
		return nil
	}
	out := new(SignatureProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDurationSensors) DeepCopyInto(out *StorageDurationSensors) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDurationSensors.
func (in *StorageDurationSensors) DeepCopy() *StorageDurationSensors {
	if in == nil {
		return nil
	}
	out := new(StorageDurationSensors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribeDataMachineConnectionsBody) DeepCopyInto(out *SubscribeDataMachineConnectionsBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribeDataMachineConnectionsBody.
func (in *SubscribeDataMachineConnectionsBody) DeepCopy() *SubscribeDataMachineConnectionsBody {
	if in == nil {
		return nil
	}
	out := new(SubscribeDataMachineConnectionsBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemsAnalysis) DeepCopyInto(out *SystemsAnalysis) {
	*out = *in
	in.Pipelines.DeepCopyInto(&out.Pipelines)
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemsAnalysis.
func (in *SystemsAnalysis) DeepCopy() *SystemsAnalysis {
	if in == nil {
		return nil
	}
	out := new(SystemsAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidContract) DeepCopyInto(out *ValidContract) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidContract.
func (in *ValidContract) DeepCopy() *ValidContract {
	if in == nil {
		return nil
	}
	out := new(ValidContract)
	in.DeepCopyInto(out)
	return out
}
