# permissions for end users to view kosmoskubeedges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kosmoskubeedge-viewer-role
rules:
- apiGroups:
  - crd.gitlab.inovex.de
  resources:
  - kosmoskubeedges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.gitlab.inovex.de
  resources:
  - kosmoskubeedges/status
  verbs:
  - get
