# permissions for end users to view kosmos-kube-edges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kosmos-kube-edge-viewer-role
rules:
- apiGroups:
  - crd.gitlab.inovex.de
  resources:
  - kosmos-kube-edges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.gitlab.inovex.de
  resources:
  - kosmos-kube-edges/status
  verbs:
  - get
