# permissions for end users to edit kosmoskubeedges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kosmoskubeedge-editor-role
rules:
  - apiGroups:
      - crd.github.inovex.de
    resources:
      - kosmoskubeedges
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - crd.github.inovex.de
    resources:
      - kosmoskubeedges/status
    verbs:
      - get
